// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ddr4869/RegiQueue/ent/course"
	"github.com/ddr4869/RegiQueue/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescCourseName is the schema descriptor for course_name field.
	courseDescCourseName := courseFields[0].Descriptor()
	// course.CourseNameValidator is a validator for the "course_name" field. It is called by the builders before save.
	course.CourseNameValidator = courseDescCourseName.Validators[0].(func(int) error)
	// courseDescUserID is the schema descriptor for user_id field.
	courseDescUserID := courseFields[1].Descriptor()
	// course.DefaultUserID holds the default value on creation for the user_id field.
	course.DefaultUserID = courseDescUserID.Default.(string)
}
